services:
    bamboo_twig_config.twig.configs:
        class: Drupal\bamboo_twig_config\TwigExtension\Configs
        arguments: ['@config.factory', '@state']
        tags:
            - { name: twig.extension }
