services:
    bamboo_twig_config.twig.config:
        class: Drupal\bamboo_twig_config\TwigExtension\Config
        arguments: ['@config.factory', '@state']
        tags:
            - { name: twig.extension }
