<?php

/**
 * @file
 */

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */use Drupal\Core\Routing\RouteMatchInterface;

/**
 *
 */
function bamboo_twig_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.bamboo_twig':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = array('settings' => $settings);
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_install().
 */
function bamboo_twig_install() {
  drupal_set_message(t("Bamboo Twig is installed and ready for action."));
}
