<?php

/**
 * @file
 * Primary module hooks for Bamboo Twig test module.
 */

/**
 * Implements hook_theme().
 */
function bamboo_twig_test_theme($existing, $type, $theme, $path) {
  return [
    'bamboo_twig_test_loader' => [
      'variables' => ['variables' => []],
      'template'  => 'loader',
    ],

    'bamboo_twig_test_security' => [
      'variables' => ['variables' => []],
      'template'  => 'security',
    ],

    'bamboo_twig_test_configs' => [
      'variables' => ['variables' => []],
      'template'  => 'configs',
    ],

    'bamboo_twig_test_files' => [
      'variables' => ['variables' => []],
      'template'  => 'files',
    ],
  ];
}
