<?php

/**
 * @file
 * Primary module hooks for Bamboo Twig test module.
 */

/**
 * Implements hook_theme().
 */
function bamboo_twig_test_theme($existing, $type, $theme, $path) {
  return [
    'bamboo_twig_test_loader' => [
      'variables' => ['variables' => []],
      'template'  => 'loader',
    ],

    'bamboo_twig_test_render' => [
      'variables' => ['variables' => []],
      'template'  => 'render',
    ],

    'bamboo_twig_test_user' => [
      'variables' => ['variables' => []],
      'template'  => 'user',
    ],

    'bamboo_twig_test_config' => [
      'variables' => ['variables' => []],
      'template'  => 'config',
    ],

    'bamboo_twig_test_files' => [
      'variables' => ['variables' => []],
      'template'  => 'files',
    ],

    'bamboo_twig_test_extensions' => [
      'variables' => ['variables' => []],
      'template'  => 'extensions',
    ],

  ];
}
