<?php

/**
 * @file
 * Primary module hooks for Bamboo Twig test module.
 */

/**
 * Implements hook_theme().
 */
function bamboo_twig_test_theme($existing, $type, $theme, $path) {
  return [
    'bamboo_twig_test_loader' => [
      'variables' => ['variables' => []],
      'template'  => 'loader',
    ],

    'bamboo_twig_test_render' => [
      'variables' => ['variables' => []],
      'template'  => 'render',
    ],

    'bamboo_twig_test_security' => [
      'variables' => ['variables' => []],
      'template'  => 'security',
    ],

    'bamboo_twig_test_configs' => [
      'variables' => ['variables' => []],
      'template'  => 'configs',
    ],

    'bamboo_twig_test_file' => [
      'variables' => ['variables' => []],
      'template'  => 'file',
    ],

    'bamboo_twig_test_path' => [
      'variables' => ['variables' => []],
      'template'  => 'path',
    ],

    'bamboo_twig_test_i18n' => [
      'variables' => ['variables' => []],
      'template'  => 'i18n',
    ],
  ];
}
